[package]
name = "file_server"
version = "0.1.0"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"

[dependencies]
serde = {version="1.0.89", features = ["derive"]}
bincode = "1.1.2"
failure = "0.1.5"
